### ISSUE TITLE
Retry specified by server is in milliseconds

### ISSUE THREAD

**Issue by ramontayag** [francois2metz/em-eventsource#14] opened 2018-10-03 05:46 UTC
I noticed that I'd disconnected and a retry wouldn't happen. I checked the headers and the retry of the server is set to 1000. This gem reads that as 1000 seconds. Reading https://html.spec.whatwg.org/multipage/server-sent-events.html#concept-event-stream-reconnection-time, I think this gem should divide the time by 1000.

Is my understanding correct?

**Comment by francois2metz** [comment] 2018-10-03 07:53
I believe you are right. I'll fix that.

**Comment by francois2metz** [comment] 2018-10-03 08:12
I believe the issue is now fixed in the 0.3.0 that I pushed to rubygems. Could you test it again please?

**Closed by francois2metz** 2018-10-03 08:12 UTC

**Comment by ramontayag** [comment] 2018-10-03 09:33
Great! It works! Thanks.

Now, I hope to get help as to why I'm getting disconnected. I'll post another issue.
